name: auto deploy

on:
  push:
    branches:
      - dev

jobs:
  docker_push_api_server:
    name: Push API Server to ncp container registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to NCP Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NCP_CONTAINER_REGISTRY }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: ./server/api-server
          file: ./server/api-server/Dockerfile
          push: true
          tags: ${{ secrets.NCP_CONTAINER_REGISTRY }}/api-server:latest
          cache-from: type=registry,ref=${{ secrets.NCP_CONTAINER_REGISTRY }}/api-server:latest
          cache-to: type=inline

  docker_push_rtmp_server:
    name: Push RTMP Server to ncp container registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to NCP Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NCP_CONTAINER_REGISTRY }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: ./server/rtmp-server
          file: ./server/rtmp-server/Dockerfile
          push: true
          tags: ${{ secrets.NCP_CONTAINER_REGISTRY }}/rtmp-server:latest
          cache-from: type=registry,ref=${{ secrets.NCP_CONTAINER_REGISTRY }}/rtmp-server:latest
          cache-to: type=inline

  docker_pull_api_server:
    name: Connect server ssh and pull api server from container registry
    needs: docker_push_api_server
    runs-on: ubuntu-latest
    steps:
      - name: connect ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_SERVER_HOST }}
          username: ${{ secrets.API_SERVER_USERNAME }}
          password: ${{ secrets.API_SERVER_PASSWORD }}
          port: ${{ secrets.API_SERVER_PORT }}
          script: |
            docker pull ${{ secrets.NCP_CONTAINER_REGISTRY }}/api-server
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker run -d -p 80:3000 --env-file ${{ secrets.ENV_PATH }} ${{ secrets.REDIS_URL}} ${{ secrets.NCP_CONTAINER_REGISTRY }}/api-server
            docker image prune -f

  docker_pull_rtmp_server:
    name: Connect server ssh and pull rtmp server from container registry
    needs: docker_push_rtmp_server
    runs-on: ubuntu-latest
    steps:
      - name: connect ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RTMP_SERVER_HOST }}
          username: ${{ secrets.RTMP_SERVER_USERNAME }}
          password: ${{ secrets.RTMP_SERVER_PASSWORD }}
          port: ${{ secrets.RTMP_SERVER_PORT }}
          script: |
            docker pull ${{ secrets.NCP_CONTAINER_REGISTRY }}/rtmp-server
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker run -d -p 1935:1935 -p 80:80 --env-file ${{ secrets.ENV_PATH }} ${{ secrets.NCP_CONTAINER_REGISTRY }}/rtmp-server
            docker image prune -f

  docker_push_front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to NCP Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NCP_CONTAINER_REGISTRY }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./client/Dockerfile
          push: true
          tags: ${{ secrets.NCP_CONTAINER_REGISTRY }}/front
          cache-from: type=registry,ref=${{ secrets.NCP_CONTAINER_REGISTRY }}/front
          cache-to: type=inline

  docker_pull_front:
    name: Connect server ssh and pull frontend from container registry
    needs: docker_push_front
    runs-on: ubuntu-latest
    steps:
      - name: connect ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FRONT_HOST }}
          username: ${{ secrets.FRONT_USERNAME }}
          password: ${{ secrets.FRONT_PASSWORD }}
          port: ${{ secrets.FRONT_PORT }}
          script: |
            docker pull ${{ secrets.NCP_CONTAINER_REGISTRY }}/front
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker run -d -p 80:80 ${{ secrets.NCP_CONTAINER_REGISTRY }}/front
            docker image prune -f
